name: Vendedor360 DataHub - Hourly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # run every hour

jobs:
  datahub:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SHEET_NAME: Vendedor360_DataHub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Escribir el JSON de la cuenta de servicio en un archivo temporal y exportar su ruta
      - name: Write service account file from secret
        run: |
          FILE_PATH="$RUNNER_TEMP/service_account.json"
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > "$FILE_PATH"
          # Exportar GOOGLE_SERVICE_ACCOUNT_JSON para los pasos siguientes
          echo "GOOGLE_SERVICE_ACCOUNT_JSON=$FILE_PATH" >> $GITHUB_ENV

      - name: Update Inventario
        run: |
          python jobs/update_inventory.py

      - name: Update Licitaciones
        run: |
          python jobs/update_bids.py

      - name: Update Marketing
        run: |
          python jobs/update_marketing.py

      - name: Commit logs/artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # A침adir 'logs' s칩lo si existe
          if [ -d logs ]; then
            git add logs/
          fi
          # A침adir 'artifacts' s칩lo si existe
          if [ -d artifacts ]; then
            git add artifacts/
          fi
          # Comprobar si hay cambios para commitear
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore(actions): update datahub logs"
            git push
          fi
